################################################################################
reader_1:
  sn: "001625127C5A"
  active: true

  antenna_1:
    active: true
    x: 0.07 # -0.025
    y: 0.0  # 0.025
    z: 0.73 # 0.5884

  antenna_2:
    active: true
    x: -0.025
    y: 0.03 #0.025
    z: 0.81 #0.8684

  antenna_3:
    active: true
    x: -0.025
    y: -0.03 #-0.025
    z: 0.81 #0.8684

  antenna_4:
    active: true
    x: -0.025
    y: -0.025
    z: 1.4884
