#footprint: []
robot_radius: 0.20

#update_frequency: 1.0
#publish_frequency: 1.0
transform_tolerance: 0.5

#must match incoming static map
global_frame: /map
robot_base_frame: /base_link
resolution: 0.025

rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}

static:
#Can pull data from gmapping, map_server or a non-rolling costmap
#map_topic: /map
#map_topic: /move_base/global_costmap/costmap
  subscribe_to_updates: true

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: closest # middle, centroid, closest
#set to false for gmapping, true if re-exploring a known area
#explore_clear_space: true

sensor:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, raytrace_range: $(arg sensor_range), obstacle_range: $(arg sensor_range)}

inflation:
  # I would suggest setting this to a value somewhat larger
  # (not too large, mind you) compared to
  # costmap_common_params.yaml/inflation_layer/inflation_radius
  inflation_radius: 0.25
